## 异常

throw一个封装了错误信息的对象，这个方法会立刻退出，并不返回任何值。

异常都是派生于Throwable类的一个实例。

由程序错误导致的异常属于RuntimeException，而程序本身没有问题，但由于IO错误这类问题导致的异常属于其他异常。

**如果出现RuntimeException异常，那么一定是你的问题**

ArithmeticException是RuntimeException

如果在子类中覆盖了超类的一个方法，子类方法中声明的受查异常不能比超类方法中声明的异常更通用(子类方法中可以抛出更特定的异常，或者根本不抛出任何异常)。

### 异常处理

### 1. 定义异常

1. 对于已经存在的异常类，将其抛出的步骤

    1. 找一个合适的异常类
    2. 创建这个类的一个对象(构造函数接受异常的描述)
    3. 将对象抛出
    
2. 创建异常类

    1. 如果任何标准异常类没有能够充分描述清楚的问题，在这种情况下，创建自己的异常类。

    2. 定义一个派生于Exception的类，或者派生于Exception子类的类。习惯性定义两个构造器，一个是默认的构造器，另外一个是带有详细信息的构造器

       ```java
       public class MyException extends Exception {
          public MyException(){}
          //给出具体描述信息的异常
          public MyException(String gripe){
              super(gripe);
         
          }
       }
       ```

       ```java
       public static int calculate(int i,int j) throws MyException{
           if(j==0||i==0)
               //抛出自己定义的异常
               throw new MyException(i+" or "+j+" shouldn't be zero");
           else
               return i/j;
       }
       ```

### 2. 捕获异常

如果某个异常发生的时候没有在任何地方进行捕获，那程序就会终止执行，并在控制台打印出异常信息。其中包括异常的类型和堆栈的内容。

如果在try语句块中的任何代码抛出一个在catch子句中说明的异常类，那么程序就跳过try语句块的其他代码。程序执行catch语句块。

1. 捕获多个异常

   ```java
   try{
       
   }catch(Exception1 e){
       //processing 
   }catch(Exception2 e){
       //processing
   }
   ```

2. Java7之后

   当处理多个异常类型采用相同的动作时，可以合并catch子句

   ```java
   try{
       
   }catch(Exception1|Exception2 e){
       //same process behavior
   }
   ```

### 3.finally子句

* 当finally子句包含return语句时，假设利用return语句从try块中退出，在方法返回之前，finally子句的内容将会执行，如果finally子句也有一个return语句，这个返回值将会覆盖原始的返回值。

  ```java
  public static int f(int n)
  {
      try{
          int r=n*n;
          return r;
      }finally {
          if(n==2) return 0;
      }
  }
  public static void main(String[]args){
      //n的结果是0
      int n=f(2);
  }
  ```

### 4. 带有资源的try语句

假设资源属于一个实现AutoCloseable接口的类，JavaSE 7提供了关闭资源的便捷方式。

```java
public static void withResourceTry(){
    //当退出try块之后，自动关闭资源
    try(Scanner in=new Scanner(new FileInputStream("C://Users//geoge//Desktop//异常.md"),
            StandardCharsets.UTF_8))
    {
        String line=in.nextLine();
        System.out.println(line);
    }
    catch (IOException e)
    {
        e.printStackTrace();
    }
}
```

try块可以指定多个资源

```java
try(Scanner in=new Scanner(new FileInputStream("/usr/local/data.txt","UTF-8"));
   PrintWriter out=new PrintWriter("out.txt"))
{
    
}cathch(IOException e){
    e.printStackTrace();
}
```

保存异常的堆栈轨迹

```java
    public static void withResourceTry(){
        try(Scanner in=new Scanner(new FileInputStream("C://Users//geoge//Desktop//异常1.md"),
                StandardCharsets.UTF_8))
        {
            String line=in.nextLine();
            System.out.println(line);
        }
        catch (IOException e)
        {
            //出现异常的语句的调用栈
            StackTraceElement[] stackTrace = e.getStackTrace();
            for(StackTraceElement s:stackTrace)
                System.out.println(s);
        }
    }
```

递归时，进行栈帧分析，分析递归时可以用这种方法分析

```java
    public static int factorial(int n)
    {
        System.out.println("factorial("+n+");");
        //获取当前的栈帧
        Throwable t=new Throwable();
        StackTraceElement[]frames=t.getStackTrace();
        //打印栈帧
        for(StackTraceElement f:frames)
            System.out.println(f);
        int r;
        if(n<=1) r=1;
        else
            r=n*factorial(n-1);
        System.out.println("return "+r);
        return r;
    }
```













